[workspace]

members = [
  "crates/vic",
  "crates/vicuna-compiler",
  "crates/vicuna-formatter",
  "crates/vicuna-wasm",
]

[workspace.dependencies]
anyhow = { version = "1.0.66", features = ["backtrace"] }
