#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 69
#define LARGE_STATE_COUNT 20
#define SYMBOL_COUNT 28
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 7

enum {
  anon_sym_LF = 1,
  anon_sym_STAR = 2,
  anon_sym_PLUS = 3,
  anon_sym_SLASH = 4,
  anon_sym_DASH = 5,
  anon_sym_BANG = 6,
  anon_sym_LPAREN = 7,
  anon_sym_COMMA = 8,
  anon_sym_RPAREN = 9,
  sym_variable = 10,
  anon_sym_true = 11,
  anon_sym_false = 12,
  sym_float = 13,
  sym_integer = 14,
  sym_string = 15,
  sym_source_file = 16,
  sym__expression = 17,
  sym__arithmetic_expression = 18,
  sym_binary_expression = 19,
  sym_unary_expression = 20,
  sym_call_expression = 21,
  sym_primary_expression = 22,
  sym_value = 23,
  sym_boolean = 24,
  aux_sym_source_file_repeat1 = 25,
  aux_sym_call_expression_repeat1 = 26,
  aux_sym_call_expression_repeat2 = 27,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_STAR] = "*",
  [anon_sym_PLUS] = "+",
  [anon_sym_SLASH] = "/",
  [anon_sym_DASH] = "-",
  [anon_sym_BANG] = "!",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [sym_variable] = "variable",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_float] = "float",
  [sym_integer] = "integer",
  [sym_string] = "string",
  [sym_source_file] = "source_file",
  [sym__expression] = "_expression",
  [sym__arithmetic_expression] = "_arithmetic_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_call_expression] = "call_expression",
  [sym_primary_expression] = "primary_expression",
  [sym_value] = "value",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_call_expression_repeat1] = "call_expression_repeat1",
  [aux_sym_call_expression_repeat2] = "call_expression_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_variable] = sym_variable,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_float] = sym_float,
  [sym_integer] = sym_integer,
  [sym_string] = sym_string,
  [sym_source_file] = sym_source_file,
  [sym__expression] = sym__expression,
  [sym__arithmetic_expression] = sym__arithmetic_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_call_expression] = sym_call_expression,
  [sym_primary_expression] = sym_primary_expression,
  [sym_value] = sym_value,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_call_expression_repeat1] = aux_sym_call_expression_repeat1,
  [aux_sym_call_expression_repeat2] = aux_sym_call_expression_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__arithmetic_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_primary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_expression_repeat2] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_arguments = 1,
  field_callee = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_callee] = "callee",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 3},
  [6] = {.index = 10, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_callee, 0},
  [1] =
    {field_arguments, 1, .inherited = true},
    {field_callee, 0},
  [3] =
    {field_arguments, 0},
    {field_arguments, 1},
  [5] =
    {field_arguments, 0, .inherited = true},
    {field_arguments, 1, .inherited = true},
  [7] =
    {field_arguments, 0},
    {field_arguments, 1},
    {field_arguments, 2},
  [10] =
    {field_arguments, 0},
    {field_arguments, 1},
    {field_arguments, 2},
    {field_arguments, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      if (lookahead == '!') ADVANCE(10);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '(') ADVANCE(11);
      if (lookahead == ')') ADVANCE(13);
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '+') ADVANCE(7);
      if (lookahead == ',') ADVANCE(12);
      if (lookahead == '-') ADVANCE(9);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == 'f') ADVANCE(14);
      if (lookahead == 't') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(26);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 3:
      if (eof) ADVANCE(4);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == '(') ADVANCE(11);
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '+') ADVANCE(7);
      if (lookahead == '-') ADVANCE(9);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(5);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'a') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'e') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'e') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'l') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'r') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 's') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'u') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_variable);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 3},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(68),
    [sym__expression] = STATE(62),
    [sym__arithmetic_expression] = STATE(62),
    [sym_binary_expression] = STATE(62),
    [sym_unary_expression] = STATE(62),
    [sym_call_expression] = STATE(62),
    [sym_primary_expression] = STATE(26),
    [sym_value] = STATE(36),
    [sym_boolean] = STATE(32),
    [aux_sym_source_file_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_BANG] = ACTIONS(5),
    [sym_variable] = ACTIONS(7),
    [anon_sym_true] = ACTIONS(9),
    [anon_sym_false] = ACTIONS(9),
    [sym_float] = ACTIONS(11),
    [sym_integer] = ACTIONS(13),
    [sym_string] = ACTIONS(11),
  },
  [2] = {
    [sym__expression] = STATE(44),
    [sym__arithmetic_expression] = STATE(44),
    [sym_binary_expression] = STATE(44),
    [sym_unary_expression] = STATE(44),
    [sym_call_expression] = STATE(44),
    [sym_primary_expression] = STATE(22),
    [sym_value] = STATE(33),
    [sym_boolean] = STATE(28),
    [aux_sym_call_expression_repeat1] = STATE(5),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_BANG] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(17),
    [sym_variable] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_float] = ACTIONS(23),
    [sym_integer] = ACTIONS(25),
    [sym_string] = ACTIONS(23),
  },
  [3] = {
    [sym__expression] = STATE(53),
    [sym__arithmetic_expression] = STATE(53),
    [sym_binary_expression] = STATE(53),
    [sym_unary_expression] = STATE(53),
    [sym_call_expression] = STATE(53),
    [sym_primary_expression] = STATE(22),
    [sym_value] = STATE(33),
    [sym_boolean] = STATE(28),
    [aux_sym_call_expression_repeat1] = STATE(10),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_BANG] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(27),
    [sym_variable] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_float] = ACTIONS(23),
    [sym_integer] = ACTIONS(25),
    [sym_string] = ACTIONS(23),
  },
  [4] = {
    [sym__expression] = STATE(66),
    [sym__arithmetic_expression] = STATE(66),
    [sym_binary_expression] = STATE(66),
    [sym_unary_expression] = STATE(66),
    [sym_call_expression] = STATE(66),
    [sym_primary_expression] = STATE(22),
    [sym_value] = STATE(33),
    [sym_boolean] = STATE(28),
    [aux_sym_call_expression_repeat1] = STATE(4),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_BANG] = ACTIONS(29),
    [anon_sym_RPAREN] = ACTIONS(32),
    [sym_variable] = ACTIONS(34),
    [anon_sym_true] = ACTIONS(37),
    [anon_sym_false] = ACTIONS(37),
    [sym_float] = ACTIONS(40),
    [sym_integer] = ACTIONS(43),
    [sym_string] = ACTIONS(40),
  },
  [5] = {
    [sym__expression] = STATE(52),
    [sym__arithmetic_expression] = STATE(52),
    [sym_binary_expression] = STATE(52),
    [sym_unary_expression] = STATE(52),
    [sym_call_expression] = STATE(52),
    [sym_primary_expression] = STATE(22),
    [sym_value] = STATE(33),
    [sym_boolean] = STATE(28),
    [aux_sym_call_expression_repeat1] = STATE(4),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_BANG] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(46),
    [sym_variable] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_float] = ACTIONS(23),
    [sym_integer] = ACTIONS(25),
    [sym_string] = ACTIONS(23),
  },
  [6] = {
    [sym__expression] = STATE(59),
    [sym__arithmetic_expression] = STATE(59),
    [sym_binary_expression] = STATE(59),
    [sym_unary_expression] = STATE(59),
    [sym_call_expression] = STATE(59),
    [sym_primary_expression] = STATE(22),
    [sym_value] = STATE(33),
    [sym_boolean] = STATE(28),
    [aux_sym_call_expression_repeat1] = STATE(4),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_BANG] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(48),
    [sym_variable] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_float] = ACTIONS(23),
    [sym_integer] = ACTIONS(25),
    [sym_string] = ACTIONS(23),
  },
  [7] = {
    [sym__expression] = STATE(61),
    [sym__arithmetic_expression] = STATE(61),
    [sym_binary_expression] = STATE(61),
    [sym_unary_expression] = STATE(61),
    [sym_call_expression] = STATE(61),
    [sym_primary_expression] = STATE(22),
    [sym_value] = STATE(33),
    [sym_boolean] = STATE(28),
    [aux_sym_call_expression_repeat1] = STATE(6),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_BANG] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(50),
    [sym_variable] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_float] = ACTIONS(23),
    [sym_integer] = ACTIONS(25),
    [sym_string] = ACTIONS(23),
  },
  [8] = {
    [sym__expression] = STATE(63),
    [sym__arithmetic_expression] = STATE(63),
    [sym_binary_expression] = STATE(63),
    [sym_unary_expression] = STATE(63),
    [sym_call_expression] = STATE(63),
    [sym_primary_expression] = STATE(40),
    [sym_value] = STATE(46),
    [sym_boolean] = STATE(48),
    [aux_sym_source_file_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(52),
    [anon_sym_DASH] = ACTIONS(54),
    [anon_sym_BANG] = ACTIONS(54),
    [sym_variable] = ACTIONS(57),
    [anon_sym_true] = ACTIONS(60),
    [anon_sym_false] = ACTIONS(60),
    [sym_float] = ACTIONS(63),
    [sym_integer] = ACTIONS(66),
    [sym_string] = ACTIONS(63),
  },
  [9] = {
    [sym__expression] = STATE(43),
    [sym__arithmetic_expression] = STATE(43),
    [sym_binary_expression] = STATE(43),
    [sym_unary_expression] = STATE(43),
    [sym_call_expression] = STATE(43),
    [sym_primary_expression] = STATE(26),
    [sym_value] = STATE(36),
    [sym_boolean] = STATE(32),
    [aux_sym_source_file_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(69),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_BANG] = ACTIONS(5),
    [sym_variable] = ACTIONS(7),
    [anon_sym_true] = ACTIONS(9),
    [anon_sym_false] = ACTIONS(9),
    [sym_float] = ACTIONS(11),
    [sym_integer] = ACTIONS(13),
    [sym_string] = ACTIONS(11),
  },
  [10] = {
    [sym__expression] = STATE(49),
    [sym__arithmetic_expression] = STATE(49),
    [sym_binary_expression] = STATE(49),
    [sym_unary_expression] = STATE(49),
    [sym_call_expression] = STATE(49),
    [sym_primary_expression] = STATE(22),
    [sym_value] = STATE(33),
    [sym_boolean] = STATE(28),
    [aux_sym_call_expression_repeat1] = STATE(4),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_BANG] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(71),
    [sym_variable] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_float] = ACTIONS(23),
    [sym_integer] = ACTIONS(25),
    [sym_string] = ACTIONS(23),
  },
  [11] = {
    [sym__expression] = STATE(65),
    [sym__arithmetic_expression] = STATE(65),
    [sym_binary_expression] = STATE(65),
    [sym_unary_expression] = STATE(65),
    [sym_call_expression] = STATE(65),
    [sym_primary_expression] = STATE(40),
    [sym_value] = STATE(46),
    [sym_boolean] = STATE(48),
    [anon_sym_DASH] = ACTIONS(73),
    [anon_sym_BANG] = ACTIONS(73),
    [sym_variable] = ACTIONS(75),
    [anon_sym_true] = ACTIONS(77),
    [anon_sym_false] = ACTIONS(77),
    [sym_float] = ACTIONS(79),
    [sym_integer] = ACTIONS(81),
    [sym_string] = ACTIONS(79),
  },
  [12] = {
    [sym__expression] = STATE(51),
    [sym__arithmetic_expression] = STATE(51),
    [sym_binary_expression] = STATE(51),
    [sym_unary_expression] = STATE(51),
    [sym_call_expression] = STATE(51),
    [sym_primary_expression] = STATE(26),
    [sym_value] = STATE(36),
    [sym_boolean] = STATE(32),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_BANG] = ACTIONS(5),
    [sym_variable] = ACTIONS(7),
    [anon_sym_true] = ACTIONS(9),
    [anon_sym_false] = ACTIONS(9),
    [sym_float] = ACTIONS(11),
    [sym_integer] = ACTIONS(13),
    [sym_string] = ACTIONS(11),
  },
  [13] = {
    [sym__expression] = STATE(50),
    [sym__arithmetic_expression] = STATE(50),
    [sym_binary_expression] = STATE(50),
    [sym_unary_expression] = STATE(50),
    [sym_call_expression] = STATE(50),
    [sym_primary_expression] = STATE(26),
    [sym_value] = STATE(36),
    [sym_boolean] = STATE(32),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_BANG] = ACTIONS(5),
    [sym_variable] = ACTIONS(7),
    [anon_sym_true] = ACTIONS(9),
    [anon_sym_false] = ACTIONS(9),
    [sym_float] = ACTIONS(11),
    [sym_integer] = ACTIONS(13),
    [sym_string] = ACTIONS(11),
  },
  [14] = {
    [sym__expression] = STATE(67),
    [sym__arithmetic_expression] = STATE(67),
    [sym_binary_expression] = STATE(67),
    [sym_unary_expression] = STATE(67),
    [sym_call_expression] = STATE(67),
    [sym_primary_expression] = STATE(40),
    [sym_value] = STATE(46),
    [sym_boolean] = STATE(48),
    [anon_sym_DASH] = ACTIONS(73),
    [anon_sym_BANG] = ACTIONS(73),
    [sym_variable] = ACTIONS(75),
    [anon_sym_true] = ACTIONS(77),
    [anon_sym_false] = ACTIONS(77),
    [sym_float] = ACTIONS(79),
    [sym_integer] = ACTIONS(81),
    [sym_string] = ACTIONS(79),
  },
  [15] = {
    [sym__expression] = STATE(54),
    [sym__arithmetic_expression] = STATE(54),
    [sym_binary_expression] = STATE(54),
    [sym_unary_expression] = STATE(54),
    [sym_call_expression] = STATE(54),
    [sym_primary_expression] = STATE(22),
    [sym_value] = STATE(33),
    [sym_boolean] = STATE(28),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_BANG] = ACTIONS(15),
    [sym_variable] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_float] = ACTIONS(23),
    [sym_integer] = ACTIONS(25),
    [sym_string] = ACTIONS(23),
  },
  [16] = {
    [sym__expression] = STATE(45),
    [sym__arithmetic_expression] = STATE(45),
    [sym_binary_expression] = STATE(45),
    [sym_unary_expression] = STATE(45),
    [sym_call_expression] = STATE(45),
    [sym_primary_expression] = STATE(22),
    [sym_value] = STATE(33),
    [sym_boolean] = STATE(28),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_BANG] = ACTIONS(15),
    [sym_variable] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_float] = ACTIONS(23),
    [sym_integer] = ACTIONS(25),
    [sym_string] = ACTIONS(23),
  },
  [17] = {
    [sym__expression] = STATE(56),
    [sym__arithmetic_expression] = STATE(56),
    [sym_binary_expression] = STATE(56),
    [sym_unary_expression] = STATE(56),
    [sym_call_expression] = STATE(56),
    [sym_primary_expression] = STATE(22),
    [sym_value] = STATE(33),
    [sym_boolean] = STATE(28),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_BANG] = ACTIONS(15),
    [sym_variable] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_float] = ACTIONS(23),
    [sym_integer] = ACTIONS(25),
    [sym_string] = ACTIONS(23),
  },
  [18] = {
    [sym__expression] = STATE(60),
    [sym__arithmetic_expression] = STATE(60),
    [sym_binary_expression] = STATE(60),
    [sym_unary_expression] = STATE(60),
    [sym_call_expression] = STATE(60),
    [sym_primary_expression] = STATE(26),
    [sym_value] = STATE(36),
    [sym_boolean] = STATE(32),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_BANG] = ACTIONS(5),
    [sym_variable] = ACTIONS(7),
    [anon_sym_true] = ACTIONS(9),
    [anon_sym_false] = ACTIONS(9),
    [sym_float] = ACTIONS(11),
    [sym_integer] = ACTIONS(13),
    [sym_string] = ACTIONS(11),
  },
  [19] = {
    [sym__expression] = STATE(64),
    [sym__arithmetic_expression] = STATE(64),
    [sym_binary_expression] = STATE(64),
    [sym_unary_expression] = STATE(64),
    [sym_call_expression] = STATE(64),
    [sym_primary_expression] = STATE(40),
    [sym_value] = STATE(46),
    [sym_boolean] = STATE(48),
    [anon_sym_DASH] = ACTIONS(73),
    [anon_sym_BANG] = ACTIONS(73),
    [sym_variable] = ACTIONS(75),
    [anon_sym_true] = ACTIONS(77),
    [anon_sym_false] = ACTIONS(77),
    [sym_float] = ACTIONS(79),
    [sym_integer] = ACTIONS(81),
    [sym_string] = ACTIONS(79),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(83), 4,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
    ACTIONS(52), 5,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
  [14] = 2,
    ACTIONS(85), 4,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
    ACTIONS(32), 5,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_RPAREN,
      sym_float,
      sym_string,
  [28] = 3,
    ACTIONS(89), 1,
      anon_sym_LPAREN,
    STATE(25), 1,
      aux_sym_call_expression_repeat2,
    ACTIONS(87), 6,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [43] = 4,
    ACTIONS(95), 1,
      anon_sym_LPAREN,
    STATE(27), 1,
      aux_sym_call_expression_repeat2,
    ACTIONS(91), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(93), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
  [60] = 3,
    ACTIONS(99), 1,
      anon_sym_LPAREN,
    STATE(24), 1,
      aux_sym_call_expression_repeat2,
    ACTIONS(97), 6,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [75] = 3,
    ACTIONS(89), 1,
      anon_sym_LPAREN,
    STATE(24), 1,
      aux_sym_call_expression_repeat2,
    ACTIONS(91), 6,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [90] = 4,
    ACTIONS(95), 1,
      anon_sym_LPAREN,
    STATE(23), 1,
      aux_sym_call_expression_repeat2,
    ACTIONS(87), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(102), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
  [107] = 4,
    ACTIONS(106), 1,
      anon_sym_LPAREN,
    STATE(27), 1,
      aux_sym_call_expression_repeat2,
    ACTIONS(97), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(104), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
  [124] = 1,
    ACTIONS(109), 7,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [134] = 1,
    ACTIONS(111), 7,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [144] = 2,
    ACTIONS(113), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(115), 5,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_LPAREN,
  [156] = 2,
    ACTIONS(117), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(119), 5,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_LPAREN,
  [168] = 2,
    ACTIONS(109), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(121), 5,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_LPAREN,
  [180] = 1,
    ACTIONS(123), 7,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [190] = 1,
    ACTIONS(113), 7,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [200] = 2,
    ACTIONS(111), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(125), 5,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_LPAREN,
  [212] = 2,
    ACTIONS(123), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(127), 5,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_LPAREN,
  [224] = 4,
    ACTIONS(97), 1,
      anon_sym_LF,
    ACTIONS(129), 1,
      anon_sym_LPAREN,
    STATE(37), 1,
      aux_sym_call_expression_repeat2,
    ACTIONS(104), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
  [240] = 4,
    ACTIONS(91), 1,
      anon_sym_LF,
    ACTIONS(132), 1,
      anon_sym_LPAREN,
    STATE(37), 1,
      aux_sym_call_expression_repeat2,
    ACTIONS(93), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
  [256] = 1,
    ACTIONS(117), 7,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [266] = 4,
    ACTIONS(87), 1,
      anon_sym_LF,
    ACTIONS(132), 1,
      anon_sym_LPAREN,
    STATE(38), 1,
      aux_sym_call_expression_repeat2,
    ACTIONS(102), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
  [282] = 1,
    ACTIONS(134), 7,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [292] = 2,
    ACTIONS(134), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(136), 5,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_LPAREN,
  [304] = 4,
    ACTIONS(138), 1,
      ts_builtin_sym_end,
    ACTIONS(140), 1,
      anon_sym_LF,
    ACTIONS(142), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(144), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [319] = 4,
    ACTIONS(46), 1,
      anon_sym_RPAREN,
    ACTIONS(150), 1,
      anon_sym_COMMA,
    ACTIONS(146), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(148), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [334] = 2,
    ACTIONS(146), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(152), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [345] = 2,
    ACTIONS(123), 1,
      anon_sym_LF,
    ACTIONS(127), 5,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_LPAREN,
  [356] = 2,
    ACTIONS(113), 1,
      anon_sym_LF,
    ACTIONS(115), 5,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_LPAREN,
  [367] = 2,
    ACTIONS(109), 1,
      anon_sym_LF,
    ACTIONS(121), 5,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_LPAREN,
  [378] = 4,
    ACTIONS(150), 1,
      anon_sym_COMMA,
    ACTIONS(154), 1,
      anon_sym_RPAREN,
    ACTIONS(146), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(148), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [393] = 3,
    ACTIONS(142), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(152), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(156), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [406] = 2,
    ACTIONS(152), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(156), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
  [417] = 4,
    ACTIONS(150), 1,
      anon_sym_COMMA,
    ACTIONS(158), 1,
      anon_sym_RPAREN,
    ACTIONS(146), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(148), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [432] = 4,
    ACTIONS(71), 1,
      anon_sym_RPAREN,
    ACTIONS(150), 1,
      anon_sym_COMMA,
    ACTIONS(146), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(148), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [447] = 1,
    ACTIONS(160), 6,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [456] = 2,
    ACTIONS(134), 1,
      anon_sym_LF,
    ACTIONS(136), 5,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_LPAREN,
  [467] = 1,
    ACTIONS(152), 6,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [476] = 2,
    ACTIONS(111), 1,
      anon_sym_LF,
    ACTIONS(125), 5,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_LPAREN,
  [487] = 2,
    ACTIONS(117), 1,
      anon_sym_LF,
    ACTIONS(119), 5,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_LPAREN,
  [498] = 4,
    ACTIONS(150), 1,
      anon_sym_COMMA,
    ACTIONS(162), 1,
      anon_sym_RPAREN,
    ACTIONS(146), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(148), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [513] = 2,
    ACTIONS(160), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(164), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
  [524] = 4,
    ACTIONS(48), 1,
      anon_sym_RPAREN,
    ACTIONS(150), 1,
      anon_sym_COMMA,
    ACTIONS(146), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(148), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [539] = 4,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
    ACTIONS(140), 1,
      anon_sym_LF,
    ACTIONS(142), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(144), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [554] = 3,
    ACTIONS(140), 1,
      anon_sym_LF,
    ACTIONS(166), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(168), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [566] = 3,
    ACTIONS(152), 1,
      anon_sym_LF,
    ACTIONS(156), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(166), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [578] = 2,
    ACTIONS(152), 1,
      anon_sym_LF,
    ACTIONS(156), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
  [588] = 3,
    ACTIONS(150), 1,
      anon_sym_COMMA,
    ACTIONS(146), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(148), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [600] = 2,
    ACTIONS(160), 1,
      anon_sym_LF,
    ACTIONS(164), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
  [610] = 1,
    ACTIONS(170), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(20)] = 0,
  [SMALL_STATE(21)] = 14,
  [SMALL_STATE(22)] = 28,
  [SMALL_STATE(23)] = 43,
  [SMALL_STATE(24)] = 60,
  [SMALL_STATE(25)] = 75,
  [SMALL_STATE(26)] = 90,
  [SMALL_STATE(27)] = 107,
  [SMALL_STATE(28)] = 124,
  [SMALL_STATE(29)] = 134,
  [SMALL_STATE(30)] = 144,
  [SMALL_STATE(31)] = 156,
  [SMALL_STATE(32)] = 168,
  [SMALL_STATE(33)] = 180,
  [SMALL_STATE(34)] = 190,
  [SMALL_STATE(35)] = 200,
  [SMALL_STATE(36)] = 212,
  [SMALL_STATE(37)] = 224,
  [SMALL_STATE(38)] = 240,
  [SMALL_STATE(39)] = 256,
  [SMALL_STATE(40)] = 266,
  [SMALL_STATE(41)] = 282,
  [SMALL_STATE(42)] = 292,
  [SMALL_STATE(43)] = 304,
  [SMALL_STATE(44)] = 319,
  [SMALL_STATE(45)] = 334,
  [SMALL_STATE(46)] = 345,
  [SMALL_STATE(47)] = 356,
  [SMALL_STATE(48)] = 367,
  [SMALL_STATE(49)] = 378,
  [SMALL_STATE(50)] = 393,
  [SMALL_STATE(51)] = 406,
  [SMALL_STATE(52)] = 417,
  [SMALL_STATE(53)] = 432,
  [SMALL_STATE(54)] = 447,
  [SMALL_STATE(55)] = 456,
  [SMALL_STATE(56)] = 467,
  [SMALL_STATE(57)] = 476,
  [SMALL_STATE(58)] = 487,
  [SMALL_STATE(59)] = 498,
  [SMALL_STATE(60)] = 513,
  [SMALL_STATE(61)] = 524,
  [SMALL_STATE(62)] = 539,
  [SMALL_STATE(63)] = 554,
  [SMALL_STATE(64)] = 566,
  [SMALL_STATE(65)] = 578,
  [SMALL_STATE(66)] = 588,
  [SMALL_STATE(67)] = 600,
  [SMALL_STATE(68)] = 610,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_expression_repeat1, 2), SHIFT_REPEAT(15),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_expression_repeat1, 2),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_call_expression_repeat1, 2), SHIFT_REPEAT(33),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_call_expression_repeat1, 2), SHIFT_REPEAT(34),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_expression_repeat1, 2), SHIFT_REPEAT(28),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_call_expression_repeat1, 2), SHIFT_REPEAT(28),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(14),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(46),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(47),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(48),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(48),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_call_expression_repeat1, 2),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 1, .production_id = 1),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 2, .production_id = 2),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 2, .production_id = 2),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_expression_repeat2, 2, .production_id = 4),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_expression_repeat2, 2, .production_id = 4), SHIFT_REPEAT(7),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 1, .production_id = 1),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_call_expression_repeat2, 2, .production_id = 4),
  [106] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_call_expression_repeat2, 2, .production_id = 4), SHIFT_REPEAT(2),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_expression_repeat2, 3, .production_id = 5),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_expression_repeat2, 4, .production_id = 6),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_call_expression_repeat2, 4, .production_id = 6),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_expression, 1),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_call_expression_repeat2, 3, .production_id = 5),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primary_expression, 1),
  [129] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_call_expression_repeat2, 2, .production_id = 4), SHIFT_REPEAT(3),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_expression_repeat2, 2, .production_id = 3),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_call_expression_repeat2, 2, .production_id = 3),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [170] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_vicuna(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
