#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 126
#define LARGE_STATE_COUNT 26
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define PRODUCTION_ID_COUNT 17

enum {
  anon_sym_if = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_else = 4,
  anon_sym_let = 5,
  anon_sym_EQ = 6,
  anon_sym_SEMI = 7,
  anon_sym_STAR = 8,
  anon_sym_PLUS = 9,
  anon_sym_SLASH = 10,
  anon_sym_DASH = 11,
  anon_sym_BANG = 12,
  anon_sym_LPAREN = 13,
  anon_sym_COMMA = 14,
  anon_sym_RPAREN = 15,
  sym_variable = 16,
  anon_sym_true = 17,
  anon_sym_false = 18,
  sym_float = 19,
  sym_integer = 20,
  sym_string = 21,
  sym_source_file = 22,
  sym_statement = 23,
  sym_if_statement = 24,
  sym_let_declaration = 25,
  sym_let_if_declaration = 26,
  sym_expression_block = 27,
  sym_expression_statement = 28,
  sym_expression = 29,
  sym__arithmetic_expression = 30,
  sym_binary_expression = 31,
  sym_unary_expression = 32,
  sym_call_expression = 33,
  sym_call = 34,
  sym_primary_expression = 35,
  sym_value = 36,
  sym_boolean = 37,
  aux_sym_source_file_repeat1 = 38,
  aux_sym_if_statement_repeat1 = 39,
  aux_sym_expression_block_repeat1 = 40,
  aux_sym_call_expression_repeat1 = 41,
  aux_sym_call_repeat1 = 42,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_if] = "if",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_else] = "else",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_STAR] = "*",
  [anon_sym_PLUS] = "+",
  [anon_sym_SLASH] = "/",
  [anon_sym_DASH] = "-",
  [anon_sym_BANG] = "!",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [sym_variable] = "variable",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_float] = "float",
  [sym_integer] = "integer",
  [sym_string] = "string",
  [sym_source_file] = "source_file",
  [sym_statement] = "statement",
  [sym_if_statement] = "if_statement",
  [sym_let_declaration] = "let_declaration",
  [sym_let_if_declaration] = "let_if_declaration",
  [sym_expression_block] = "expression_block",
  [sym_expression_statement] = "expression_statement",
  [sym_expression] = "expression",
  [sym__arithmetic_expression] = "_arithmetic_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_call_expression] = "call_expression",
  [sym_call] = "call",
  [sym_primary_expression] = "primary_expression",
  [sym_value] = "value",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_if_statement_repeat1] = "if_statement_repeat1",
  [aux_sym_expression_block_repeat1] = "expression_block_repeat1",
  [aux_sym_call_expression_repeat1] = "call_expression_repeat1",
  [aux_sym_call_repeat1] = "call_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_variable] = sym_variable,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_float] = sym_float,
  [sym_integer] = sym_integer,
  [sym_string] = sym_string,
  [sym_source_file] = sym_source_file,
  [sym_statement] = sym_statement,
  [sym_if_statement] = sym_if_statement,
  [sym_let_declaration] = sym_let_declaration,
  [sym_let_if_declaration] = sym_let_if_declaration,
  [sym_expression_block] = sym_expression_block,
  [sym_expression_statement] = sym_expression_statement,
  [sym_expression] = sym_expression,
  [sym__arithmetic_expression] = sym__arithmetic_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_call_expression] = sym_call_expression,
  [sym_call] = sym_call,
  [sym_primary_expression] = sym_primary_expression,
  [sym_value] = sym_value,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_if_statement_repeat1] = aux_sym_if_statement_repeat1,
  [aux_sym_expression_block_repeat1] = aux_sym_expression_block_repeat1,
  [aux_sym_call_expression_repeat1] = aux_sym_call_expression_repeat1,
  [aux_sym_call_repeat1] = aux_sym_call_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_let_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_let_if_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_block] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__arithmetic_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_primary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_if_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_argument = 1,
  field_call = 2,
  field_callee = 3,
  field_condition = 4,
  field_else_block = 5,
  field_then_block = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_call] = "call",
  [field_callee] = "callee",
  [field_condition] = "condition",
  [field_else_block] = "else_block",
  [field_then_block] = "then_block",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 3},
  [5] = {.index = 8, .length = 1},
  [6] = {.index = 9, .length = 1},
  [7] = {.index = 10, .length = 1},
  [8] = {.index = 11, .length = 2},
  [9] = {.index = 13, .length = 4},
  [10] = {.index = 17, .length = 2},
  [11] = {.index = 19, .length = 2},
  [12] = {.index = 21, .length = 6},
  [13] = {.index = 27, .length = 7},
  [14] = {.index = 34, .length = 7},
  [15] = {.index = 41, .length = 4},
  [16] = {.index = 45, .length = 8},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_call, 0},
  [1] =
    {field_call, 1, .inherited = true},
    {field_callee, 0},
  [3] =
    {field_call, 0, .inherited = true},
    {field_call, 1, .inherited = true},
  [5] =
    {field_condition, 1},
    {field_then_block, 2},
    {field_then_block, 3},
  [8] =
    {field_argument, 0},
  [9] =
    {field_argument, 1},
  [10] =
    {field_argument, 1, .inherited = true},
  [11] =
    {field_argument, 0, .inherited = true},
    {field_argument, 1, .inherited = true},
  [13] =
    {field_condition, 1},
    {field_then_block, 2},
    {field_then_block, 3},
    {field_then_block, 4},
  [17] =
    {field_argument, 1, .inherited = true},
    {field_argument, 2},
  [19] =
    {field_condition, 4},
    {field_then_block, 5},
  [21] =
    {field_condition, 1},
    {field_else_block, 4},
    {field_else_block, 5},
    {field_else_block, 6},
    {field_then_block, 2},
    {field_then_block, 3},
  [27] =
    {field_condition, 1},
    {field_else_block, 4},
    {field_else_block, 5},
    {field_else_block, 6},
    {field_else_block, 7},
    {field_then_block, 2},
    {field_then_block, 3},
  [34] =
    {field_condition, 1},
    {field_else_block, 5},
    {field_else_block, 6},
    {field_else_block, 7},
    {field_then_block, 2},
    {field_then_block, 3},
    {field_then_block, 4},
  [41] =
    {field_condition, 4},
    {field_else_block, 6},
    {field_else_block, 7},
    {field_then_block, 5},
  [45] =
    {field_condition, 1},
    {field_else_block, 5},
    {field_else_block, 6},
    {field_else_block, 7},
    {field_else_block, 8},
    {field_then_block, 2},
    {field_then_block, 3},
    {field_then_block, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == '!') ADVANCE(19);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == ')') ADVANCE(22);
      if (lookahead == '*') ADVANCE(15);
      if (lookahead == '+') ADVANCE(16);
      if (lookahead == ',') ADVANCE(21);
      if (lookahead == '-') ADVANCE(18);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead == ';') ADVANCE(14);
      if (lookahead == '=') ADVANCE(13);
      if (lookahead == 'e') ADVANCE(29);
      if (lookahead == 'f') ADVANCE(23);
      if (lookahead == 'i') ADVANCE(28);
      if (lookahead == 'l') ADVANCE(24);
      if (lookahead == 't') ADVANCE(31);
      if (lookahead == '{') ADVANCE(9);
      if (lookahead == '}') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(19);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == ')') ADVANCE(22);
      if (lookahead == '-') ADVANCE(18);
      if (lookahead == 'f') ADVANCE(23);
      if (lookahead == 't') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(19);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '-') ADVANCE(18);
      if (lookahead == 'f') ADVANCE(23);
      if (lookahead == 'i') ADVANCE(28);
      if (lookahead == 't') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(41);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 5:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '!') ADVANCE(19);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '-') ADVANCE(18);
      if (lookahead == ';') ADVANCE(14);
      if (lookahead == 'f') ADVANCE(23);
      if (lookahead == 'i') ADVANCE(28);
      if (lookahead == 'l') ADVANCE(24);
      if (lookahead == 't') ADVANCE(31);
      if (lookahead == '}') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_else);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'a') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'e') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'e') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'e') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'e') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'f') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'l') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'l') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'r') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 's') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 's') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 't') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'u') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_variable);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 6},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 6},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 6},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 6},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 6},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 6},
  [56] = {.lex_state = 6},
  [57] = {.lex_state = 6},
  [58] = {.lex_state = 6},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 6},
  [61] = {.lex_state = 6},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 6},
  [66] = {.lex_state = 6},
  [67] = {.lex_state = 6},
  [68] = {.lex_state = 6},
  [69] = {.lex_state = 6},
  [70] = {.lex_state = 6},
  [71] = {.lex_state = 6},
  [72] = {.lex_state = 6},
  [73] = {.lex_state = 6},
  [74] = {.lex_state = 6},
  [75] = {.lex_state = 6},
  [76] = {.lex_state = 6},
  [77] = {.lex_state = 6},
  [78] = {.lex_state = 6},
  [79] = {.lex_state = 6},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 1},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 4},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 4},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(114),
    [sym_statement] = STATE(21),
    [sym_if_statement] = STATE(56),
    [sym_let_declaration] = STATE(56),
    [sym_let_if_declaration] = STATE(56),
    [sym_expression_statement] = STATE(56),
    [sym_expression] = STATE(107),
    [sym__arithmetic_expression] = STATE(82),
    [sym_binary_expression] = STATE(82),
    [sym_unary_expression] = STATE(82),
    [sym_call_expression] = STATE(82),
    [sym_primary_expression] = STATE(82),
    [sym_value] = STATE(88),
    [sym_boolean] = STATE(86),
    [aux_sym_source_file_repeat1] = STATE(21),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_if] = ACTIONS(5),
    [anon_sym_let] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [sym_variable] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_integer] = ACTIONS(17),
    [sym_string] = ACTIONS(15),
  },
  [2] = {
    [sym_statement] = STATE(122),
    [sym_if_statement] = STATE(56),
    [sym_let_declaration] = STATE(56),
    [sym_let_if_declaration] = STATE(56),
    [sym_expression_statement] = STATE(56),
    [sym_expression] = STATE(99),
    [sym__arithmetic_expression] = STATE(82),
    [sym_binary_expression] = STATE(82),
    [sym_unary_expression] = STATE(82),
    [sym_call_expression] = STATE(82),
    [sym_primary_expression] = STATE(82),
    [sym_value] = STATE(88),
    [sym_boolean] = STATE(86),
    [aux_sym_expression_block_repeat1] = STATE(9),
    [anon_sym_if] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(19),
    [anon_sym_let] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [sym_variable] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_integer] = ACTIONS(17),
    [sym_string] = ACTIONS(15),
  },
  [3] = {
    [sym_statement] = STATE(122),
    [sym_if_statement] = STATE(56),
    [sym_let_declaration] = STATE(56),
    [sym_let_if_declaration] = STATE(56),
    [sym_expression_statement] = STATE(56),
    [sym_expression] = STATE(101),
    [sym__arithmetic_expression] = STATE(82),
    [sym_binary_expression] = STATE(82),
    [sym_unary_expression] = STATE(82),
    [sym_call_expression] = STATE(82),
    [sym_primary_expression] = STATE(82),
    [sym_value] = STATE(88),
    [sym_boolean] = STATE(86),
    [aux_sym_expression_block_repeat1] = STATE(11),
    [anon_sym_if] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_let] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [sym_variable] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_integer] = ACTIONS(17),
    [sym_string] = ACTIONS(15),
  },
  [4] = {
    [sym_statement] = STATE(8),
    [sym_if_statement] = STATE(72),
    [sym_let_declaration] = STATE(72),
    [sym_let_if_declaration] = STATE(72),
    [sym_expression_statement] = STATE(72),
    [sym_expression] = STATE(108),
    [sym__arithmetic_expression] = STATE(82),
    [sym_binary_expression] = STATE(82),
    [sym_unary_expression] = STATE(82),
    [sym_call_expression] = STATE(82),
    [sym_primary_expression] = STATE(82),
    [sym_value] = STATE(88),
    [sym_boolean] = STATE(86),
    [aux_sym_if_statement_repeat1] = STATE(8),
    [anon_sym_if] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(27),
    [anon_sym_let] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [sym_variable] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_integer] = ACTIONS(17),
    [sym_string] = ACTIONS(15),
  },
  [5] = {
    [sym_statement] = STATE(122),
    [sym_if_statement] = STATE(56),
    [sym_let_declaration] = STATE(56),
    [sym_let_if_declaration] = STATE(56),
    [sym_expression_statement] = STATE(56),
    [sym_expression] = STATE(100),
    [sym__arithmetic_expression] = STATE(82),
    [sym_binary_expression] = STATE(82),
    [sym_unary_expression] = STATE(82),
    [sym_call_expression] = STATE(82),
    [sym_primary_expression] = STATE(82),
    [sym_value] = STATE(88),
    [sym_boolean] = STATE(86),
    [aux_sym_expression_block_repeat1] = STATE(13),
    [anon_sym_if] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(31),
    [anon_sym_let] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [sym_variable] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_integer] = ACTIONS(17),
    [sym_string] = ACTIONS(15),
  },
  [6] = {
    [sym_statement] = STATE(8),
    [sym_if_statement] = STATE(72),
    [sym_let_declaration] = STATE(72),
    [sym_let_if_declaration] = STATE(72),
    [sym_expression_statement] = STATE(72),
    [sym_expression] = STATE(108),
    [sym__arithmetic_expression] = STATE(82),
    [sym_binary_expression] = STATE(82),
    [sym_unary_expression] = STATE(82),
    [sym_call_expression] = STATE(82),
    [sym_primary_expression] = STATE(82),
    [sym_value] = STATE(88),
    [sym_boolean] = STATE(86),
    [aux_sym_if_statement_repeat1] = STATE(8),
    [anon_sym_if] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(33),
    [anon_sym_let] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [sym_variable] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_integer] = ACTIONS(17),
    [sym_string] = ACTIONS(15),
  },
  [7] = {
    [sym_statement] = STATE(122),
    [sym_if_statement] = STATE(56),
    [sym_let_declaration] = STATE(56),
    [sym_let_if_declaration] = STATE(56),
    [sym_expression_statement] = STATE(56),
    [sym_expression] = STATE(92),
    [sym__arithmetic_expression] = STATE(82),
    [sym_binary_expression] = STATE(82),
    [sym_unary_expression] = STATE(82),
    [sym_call_expression] = STATE(82),
    [sym_primary_expression] = STATE(82),
    [sym_value] = STATE(88),
    [sym_boolean] = STATE(86),
    [aux_sym_expression_block_repeat1] = STATE(5),
    [anon_sym_if] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(35),
    [anon_sym_let] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [sym_variable] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_integer] = ACTIONS(17),
    [sym_string] = ACTIONS(15),
  },
  [8] = {
    [sym_statement] = STATE(8),
    [sym_if_statement] = STATE(72),
    [sym_let_declaration] = STATE(72),
    [sym_let_if_declaration] = STATE(72),
    [sym_expression_statement] = STATE(72),
    [sym_expression] = STATE(108),
    [sym__arithmetic_expression] = STATE(82),
    [sym_binary_expression] = STATE(82),
    [sym_unary_expression] = STATE(82),
    [sym_call_expression] = STATE(82),
    [sym_primary_expression] = STATE(82),
    [sym_value] = STATE(88),
    [sym_boolean] = STATE(86),
    [aux_sym_if_statement_repeat1] = STATE(8),
    [anon_sym_if] = ACTIONS(37),
    [anon_sym_RBRACE] = ACTIONS(40),
    [anon_sym_let] = ACTIONS(42),
    [anon_sym_DASH] = ACTIONS(45),
    [anon_sym_BANG] = ACTIONS(45),
    [sym_variable] = ACTIONS(48),
    [anon_sym_true] = ACTIONS(51),
    [anon_sym_false] = ACTIONS(51),
    [sym_float] = ACTIONS(54),
    [sym_integer] = ACTIONS(57),
    [sym_string] = ACTIONS(54),
  },
  [9] = {
    [sym_statement] = STATE(122),
    [sym_if_statement] = STATE(56),
    [sym_let_declaration] = STATE(56),
    [sym_let_if_declaration] = STATE(56),
    [sym_expression_statement] = STATE(56),
    [sym_expression] = STATE(97),
    [sym__arithmetic_expression] = STATE(82),
    [sym_binary_expression] = STATE(82),
    [sym_unary_expression] = STATE(82),
    [sym_call_expression] = STATE(82),
    [sym_primary_expression] = STATE(82),
    [sym_value] = STATE(88),
    [sym_boolean] = STATE(86),
    [aux_sym_expression_block_repeat1] = STATE(13),
    [anon_sym_if] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(60),
    [anon_sym_let] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [sym_variable] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_integer] = ACTIONS(17),
    [sym_string] = ACTIONS(15),
  },
  [10] = {
    [sym_statement] = STATE(20),
    [sym_if_statement] = STATE(72),
    [sym_let_declaration] = STATE(72),
    [sym_let_if_declaration] = STATE(72),
    [sym_expression_statement] = STATE(72),
    [sym_expression] = STATE(108),
    [sym__arithmetic_expression] = STATE(82),
    [sym_binary_expression] = STATE(82),
    [sym_unary_expression] = STATE(82),
    [sym_call_expression] = STATE(82),
    [sym_primary_expression] = STATE(82),
    [sym_value] = STATE(88),
    [sym_boolean] = STATE(86),
    [aux_sym_if_statement_repeat1] = STATE(20),
    [anon_sym_if] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(62),
    [anon_sym_let] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [sym_variable] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_integer] = ACTIONS(17),
    [sym_string] = ACTIONS(15),
  },
  [11] = {
    [sym_statement] = STATE(122),
    [sym_if_statement] = STATE(56),
    [sym_let_declaration] = STATE(56),
    [sym_let_if_declaration] = STATE(56),
    [sym_expression_statement] = STATE(56),
    [sym_expression] = STATE(90),
    [sym__arithmetic_expression] = STATE(82),
    [sym_binary_expression] = STATE(82),
    [sym_unary_expression] = STATE(82),
    [sym_call_expression] = STATE(82),
    [sym_primary_expression] = STATE(82),
    [sym_value] = STATE(88),
    [sym_boolean] = STATE(86),
    [aux_sym_expression_block_repeat1] = STATE(13),
    [anon_sym_if] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(64),
    [anon_sym_let] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [sym_variable] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_integer] = ACTIONS(17),
    [sym_string] = ACTIONS(15),
  },
  [12] = {
    [sym_statement] = STATE(12),
    [sym_if_statement] = STATE(56),
    [sym_let_declaration] = STATE(56),
    [sym_let_if_declaration] = STATE(56),
    [sym_expression_statement] = STATE(56),
    [sym_expression] = STATE(107),
    [sym__arithmetic_expression] = STATE(82),
    [sym_binary_expression] = STATE(82),
    [sym_unary_expression] = STATE(82),
    [sym_call_expression] = STATE(82),
    [sym_primary_expression] = STATE(82),
    [sym_value] = STATE(88),
    [sym_boolean] = STATE(86),
    [aux_sym_source_file_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(66),
    [anon_sym_if] = ACTIONS(68),
    [anon_sym_let] = ACTIONS(71),
    [anon_sym_DASH] = ACTIONS(74),
    [anon_sym_BANG] = ACTIONS(74),
    [sym_variable] = ACTIONS(77),
    [anon_sym_true] = ACTIONS(80),
    [anon_sym_false] = ACTIONS(80),
    [sym_float] = ACTIONS(83),
    [sym_integer] = ACTIONS(86),
    [sym_string] = ACTIONS(83),
  },
  [13] = {
    [sym_statement] = STATE(122),
    [sym_if_statement] = STATE(56),
    [sym_let_declaration] = STATE(56),
    [sym_let_if_declaration] = STATE(56),
    [sym_expression_statement] = STATE(56),
    [sym_expression] = STATE(107),
    [sym__arithmetic_expression] = STATE(82),
    [sym_binary_expression] = STATE(82),
    [sym_unary_expression] = STATE(82),
    [sym_call_expression] = STATE(82),
    [sym_primary_expression] = STATE(82),
    [sym_value] = STATE(88),
    [sym_boolean] = STATE(86),
    [aux_sym_expression_block_repeat1] = STATE(13),
    [anon_sym_if] = ACTIONS(89),
    [anon_sym_RBRACE] = ACTIONS(92),
    [anon_sym_let] = ACTIONS(94),
    [anon_sym_DASH] = ACTIONS(97),
    [anon_sym_BANG] = ACTIONS(97),
    [sym_variable] = ACTIONS(100),
    [anon_sym_true] = ACTIONS(103),
    [anon_sym_false] = ACTIONS(103),
    [sym_float] = ACTIONS(106),
    [sym_integer] = ACTIONS(109),
    [sym_string] = ACTIONS(106),
  },
  [14] = {
    [sym_statement] = STATE(8),
    [sym_if_statement] = STATE(72),
    [sym_let_declaration] = STATE(72),
    [sym_let_if_declaration] = STATE(72),
    [sym_expression_statement] = STATE(72),
    [sym_expression] = STATE(108),
    [sym__arithmetic_expression] = STATE(82),
    [sym_binary_expression] = STATE(82),
    [sym_unary_expression] = STATE(82),
    [sym_call_expression] = STATE(82),
    [sym_primary_expression] = STATE(82),
    [sym_value] = STATE(88),
    [sym_boolean] = STATE(86),
    [aux_sym_if_statement_repeat1] = STATE(8),
    [anon_sym_if] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(112),
    [anon_sym_let] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [sym_variable] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_integer] = ACTIONS(17),
    [sym_string] = ACTIONS(15),
  },
  [15] = {
    [sym_statement] = STATE(122),
    [sym_if_statement] = STATE(56),
    [sym_let_declaration] = STATE(56),
    [sym_let_if_declaration] = STATE(56),
    [sym_expression_statement] = STATE(56),
    [sym_expression] = STATE(102),
    [sym__arithmetic_expression] = STATE(82),
    [sym_binary_expression] = STATE(82),
    [sym_unary_expression] = STATE(82),
    [sym_call_expression] = STATE(82),
    [sym_primary_expression] = STATE(82),
    [sym_value] = STATE(88),
    [sym_boolean] = STATE(86),
    [aux_sym_expression_block_repeat1] = STATE(13),
    [anon_sym_if] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(114),
    [anon_sym_let] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [sym_variable] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_integer] = ACTIONS(17),
    [sym_string] = ACTIONS(15),
  },
  [16] = {
    [sym_statement] = STATE(14),
    [sym_if_statement] = STATE(72),
    [sym_let_declaration] = STATE(72),
    [sym_let_if_declaration] = STATE(72),
    [sym_expression_statement] = STATE(72),
    [sym_expression] = STATE(108),
    [sym__arithmetic_expression] = STATE(82),
    [sym_binary_expression] = STATE(82),
    [sym_unary_expression] = STATE(82),
    [sym_call_expression] = STATE(82),
    [sym_primary_expression] = STATE(82),
    [sym_value] = STATE(88),
    [sym_boolean] = STATE(86),
    [aux_sym_if_statement_repeat1] = STATE(14),
    [anon_sym_if] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(116),
    [anon_sym_let] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [sym_variable] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_integer] = ACTIONS(17),
    [sym_string] = ACTIONS(15),
  },
  [17] = {
    [sym_statement] = STATE(8),
    [sym_if_statement] = STATE(72),
    [sym_let_declaration] = STATE(72),
    [sym_let_if_declaration] = STATE(72),
    [sym_expression_statement] = STATE(72),
    [sym_expression] = STATE(108),
    [sym__arithmetic_expression] = STATE(82),
    [sym_binary_expression] = STATE(82),
    [sym_unary_expression] = STATE(82),
    [sym_call_expression] = STATE(82),
    [sym_primary_expression] = STATE(82),
    [sym_value] = STATE(88),
    [sym_boolean] = STATE(86),
    [aux_sym_if_statement_repeat1] = STATE(8),
    [anon_sym_if] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(118),
    [anon_sym_let] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [sym_variable] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_integer] = ACTIONS(17),
    [sym_string] = ACTIONS(15),
  },
  [18] = {
    [sym_statement] = STATE(6),
    [sym_if_statement] = STATE(72),
    [sym_let_declaration] = STATE(72),
    [sym_let_if_declaration] = STATE(72),
    [sym_expression_statement] = STATE(72),
    [sym_expression] = STATE(108),
    [sym__arithmetic_expression] = STATE(82),
    [sym_binary_expression] = STATE(82),
    [sym_unary_expression] = STATE(82),
    [sym_call_expression] = STATE(82),
    [sym_primary_expression] = STATE(82),
    [sym_value] = STATE(88),
    [sym_boolean] = STATE(86),
    [aux_sym_if_statement_repeat1] = STATE(6),
    [anon_sym_if] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(120),
    [anon_sym_let] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [sym_variable] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_integer] = ACTIONS(17),
    [sym_string] = ACTIONS(15),
  },
  [19] = {
    [sym_statement] = STATE(122),
    [sym_if_statement] = STATE(56),
    [sym_let_declaration] = STATE(56),
    [sym_let_if_declaration] = STATE(56),
    [sym_expression_statement] = STATE(56),
    [sym_expression] = STATE(98),
    [sym__arithmetic_expression] = STATE(82),
    [sym_binary_expression] = STATE(82),
    [sym_unary_expression] = STATE(82),
    [sym_call_expression] = STATE(82),
    [sym_primary_expression] = STATE(82),
    [sym_value] = STATE(88),
    [sym_boolean] = STATE(86),
    [aux_sym_expression_block_repeat1] = STATE(15),
    [anon_sym_if] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(122),
    [anon_sym_let] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [sym_variable] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_integer] = ACTIONS(17),
    [sym_string] = ACTIONS(15),
  },
  [20] = {
    [sym_statement] = STATE(8),
    [sym_if_statement] = STATE(72),
    [sym_let_declaration] = STATE(72),
    [sym_let_if_declaration] = STATE(72),
    [sym_expression_statement] = STATE(72),
    [sym_expression] = STATE(108),
    [sym__arithmetic_expression] = STATE(82),
    [sym_binary_expression] = STATE(82),
    [sym_unary_expression] = STATE(82),
    [sym_call_expression] = STATE(82),
    [sym_primary_expression] = STATE(82),
    [sym_value] = STATE(88),
    [sym_boolean] = STATE(86),
    [aux_sym_if_statement_repeat1] = STATE(8),
    [anon_sym_if] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(124),
    [anon_sym_let] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [sym_variable] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_integer] = ACTIONS(17),
    [sym_string] = ACTIONS(15),
  },
  [21] = {
    [sym_statement] = STATE(12),
    [sym_if_statement] = STATE(56),
    [sym_let_declaration] = STATE(56),
    [sym_let_if_declaration] = STATE(56),
    [sym_expression_statement] = STATE(56),
    [sym_expression] = STATE(107),
    [sym__arithmetic_expression] = STATE(82),
    [sym_binary_expression] = STATE(82),
    [sym_unary_expression] = STATE(82),
    [sym_call_expression] = STATE(82),
    [sym_primary_expression] = STATE(82),
    [sym_value] = STATE(88),
    [sym_boolean] = STATE(86),
    [aux_sym_source_file_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(126),
    [anon_sym_if] = ACTIONS(5),
    [anon_sym_let] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [sym_variable] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_integer] = ACTIONS(17),
    [sym_string] = ACTIONS(15),
  },
  [22] = {
    [sym_statement] = STATE(17),
    [sym_if_statement] = STATE(72),
    [sym_let_declaration] = STATE(72),
    [sym_let_if_declaration] = STATE(72),
    [sym_expression_statement] = STATE(72),
    [sym_expression] = STATE(108),
    [sym__arithmetic_expression] = STATE(82),
    [sym_binary_expression] = STATE(82),
    [sym_unary_expression] = STATE(82),
    [sym_call_expression] = STATE(82),
    [sym_primary_expression] = STATE(82),
    [sym_value] = STATE(88),
    [sym_boolean] = STATE(86),
    [aux_sym_if_statement_repeat1] = STATE(17),
    [anon_sym_if] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(128),
    [anon_sym_let] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [sym_variable] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_integer] = ACTIONS(17),
    [sym_string] = ACTIONS(15),
  },
  [23] = {
    [sym_statement] = STATE(4),
    [sym_if_statement] = STATE(72),
    [sym_let_declaration] = STATE(72),
    [sym_let_if_declaration] = STATE(72),
    [sym_expression_statement] = STATE(72),
    [sym_expression] = STATE(108),
    [sym__arithmetic_expression] = STATE(82),
    [sym_binary_expression] = STATE(82),
    [sym_unary_expression] = STATE(82),
    [sym_call_expression] = STATE(82),
    [sym_primary_expression] = STATE(82),
    [sym_value] = STATE(88),
    [sym_boolean] = STATE(86),
    [aux_sym_if_statement_repeat1] = STATE(4),
    [anon_sym_if] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(130),
    [anon_sym_let] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [sym_variable] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_integer] = ACTIONS(17),
    [sym_string] = ACTIONS(15),
  },
  [24] = {
    [sym_statement] = STATE(8),
    [sym_if_statement] = STATE(72),
    [sym_let_declaration] = STATE(72),
    [sym_let_if_declaration] = STATE(72),
    [sym_expression_statement] = STATE(72),
    [sym_expression] = STATE(108),
    [sym__arithmetic_expression] = STATE(82),
    [sym_binary_expression] = STATE(82),
    [sym_unary_expression] = STATE(82),
    [sym_call_expression] = STATE(82),
    [sym_primary_expression] = STATE(82),
    [sym_value] = STATE(88),
    [sym_boolean] = STATE(86),
    [aux_sym_if_statement_repeat1] = STATE(8),
    [anon_sym_if] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(132),
    [anon_sym_let] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [sym_variable] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_integer] = ACTIONS(17),
    [sym_string] = ACTIONS(15),
  },
  [25] = {
    [sym_statement] = STATE(24),
    [sym_if_statement] = STATE(72),
    [sym_let_declaration] = STATE(72),
    [sym_let_if_declaration] = STATE(72),
    [sym_expression_statement] = STATE(72),
    [sym_expression] = STATE(108),
    [sym__arithmetic_expression] = STATE(82),
    [sym_binary_expression] = STATE(82),
    [sym_unary_expression] = STATE(82),
    [sym_call_expression] = STATE(82),
    [sym_primary_expression] = STATE(82),
    [sym_value] = STATE(88),
    [sym_boolean] = STATE(86),
    [aux_sym_if_statement_repeat1] = STATE(24),
    [anon_sym_if] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(134),
    [anon_sym_let] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [sym_variable] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_integer] = ACTIONS(17),
    [sym_string] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(11), 1,
      sym_variable,
    ACTIONS(17), 1,
      sym_integer,
    ACTIONS(136), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      aux_sym_call_repeat1,
    STATE(86), 1,
      sym_boolean,
    STATE(88), 1,
      sym_value,
    STATE(89), 1,
      sym_expression,
    ACTIONS(9), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(15), 2,
      sym_float,
      sym_string,
    STATE(82), 5,
      sym__arithmetic_expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_call_expression,
      sym_primary_expression,
  [41] = 11,
    ACTIONS(11), 1,
      sym_variable,
    ACTIONS(17), 1,
      sym_integer,
    ACTIONS(138), 1,
      anon_sym_RPAREN,
    STATE(26), 1,
      aux_sym_call_repeat1,
    STATE(86), 1,
      sym_boolean,
    STATE(88), 1,
      sym_value,
    STATE(91), 1,
      sym_expression,
    ACTIONS(9), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(15), 2,
      sym_float,
      sym_string,
    STATE(82), 5,
      sym__arithmetic_expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_call_expression,
      sym_primary_expression,
  [82] = 11,
    ACTIONS(143), 1,
      anon_sym_RPAREN,
    ACTIONS(145), 1,
      sym_variable,
    ACTIONS(154), 1,
      sym_integer,
    STATE(28), 1,
      aux_sym_call_repeat1,
    STATE(86), 1,
      sym_boolean,
    STATE(88), 1,
      sym_value,
    STATE(103), 1,
      sym_expression,
    ACTIONS(140), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(148), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(151), 2,
      sym_float,
      sym_string,
    STATE(82), 5,
      sym__arithmetic_expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_call_expression,
      sym_primary_expression,
  [123] = 10,
    ACTIONS(11), 1,
      sym_variable,
    ACTIONS(17), 1,
      sym_integer,
    ACTIONS(157), 1,
      anon_sym_if,
    STATE(86), 1,
      sym_boolean,
    STATE(88), 1,
      sym_value,
    STATE(104), 1,
      sym_expression,
    ACTIONS(9), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(15), 2,
      sym_float,
      sym_string,
    STATE(82), 5,
      sym__arithmetic_expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_call_expression,
      sym_primary_expression,
  [161] = 10,
    ACTIONS(11), 1,
      sym_variable,
    ACTIONS(17), 1,
      sym_integer,
    ACTIONS(159), 1,
      anon_sym_if,
    STATE(86), 1,
      sym_boolean,
    STATE(88), 1,
      sym_value,
    STATE(104), 1,
      sym_expression,
    ACTIONS(9), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(15), 2,
      sym_float,
      sym_string,
    STATE(82), 5,
      sym__arithmetic_expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_call_expression,
      sym_primary_expression,
  [199] = 10,
    ACTIONS(11), 1,
      sym_variable,
    ACTIONS(17), 1,
      sym_integer,
    ACTIONS(161), 1,
      anon_sym_if,
    STATE(86), 1,
      sym_boolean,
    STATE(88), 1,
      sym_value,
    STATE(106), 1,
      sym_expression,
    ACTIONS(9), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(15), 2,
      sym_float,
      sym_string,
    STATE(82), 5,
      sym__arithmetic_expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_call_expression,
      sym_primary_expression,
  [237] = 9,
    ACTIONS(11), 1,
      sym_variable,
    ACTIONS(17), 1,
      sym_integer,
    STATE(62), 1,
      sym_expression,
    STATE(86), 1,
      sym_boolean,
    STATE(88), 1,
      sym_value,
    ACTIONS(9), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(15), 2,
      sym_float,
      sym_string,
    STATE(82), 5,
      sym__arithmetic_expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_call_expression,
      sym_primary_expression,
  [272] = 9,
    ACTIONS(11), 1,
      sym_variable,
    ACTIONS(17), 1,
      sym_integer,
    STATE(86), 1,
      sym_boolean,
    STATE(88), 1,
      sym_value,
    STATE(105), 1,
      sym_expression,
    ACTIONS(9), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(15), 2,
      sym_float,
      sym_string,
    STATE(82), 5,
      sym__arithmetic_expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_call_expression,
      sym_primary_expression,
  [307] = 9,
    ACTIONS(11), 1,
      sym_variable,
    ACTIONS(17), 1,
      sym_integer,
    STATE(48), 1,
      sym_expression,
    STATE(86), 1,
      sym_boolean,
    STATE(88), 1,
      sym_value,
    ACTIONS(9), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(15), 2,
      sym_float,
      sym_string,
    STATE(82), 5,
      sym__arithmetic_expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_call_expression,
      sym_primary_expression,
  [342] = 9,
    ACTIONS(11), 1,
      sym_variable,
    ACTIONS(17), 1,
      sym_integer,
    STATE(86), 1,
      sym_boolean,
    STATE(88), 1,
      sym_value,
    STATE(94), 1,
      sym_expression,
    ACTIONS(9), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(15), 2,
      sym_float,
      sym_string,
    STATE(82), 5,
      sym__arithmetic_expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_call_expression,
      sym_primary_expression,
  [377] = 9,
    ACTIONS(11), 1,
      sym_variable,
    ACTIONS(17), 1,
      sym_integer,
    STATE(47), 1,
      sym_expression,
    STATE(86), 1,
      sym_boolean,
    STATE(88), 1,
      sym_value,
    ACTIONS(9), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(15), 2,
      sym_float,
      sym_string,
    STATE(82), 5,
      sym__arithmetic_expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_call_expression,
      sym_primary_expression,
  [412] = 9,
    ACTIONS(11), 1,
      sym_variable,
    ACTIONS(17), 1,
      sym_integer,
    STATE(86), 1,
      sym_boolean,
    STATE(88), 1,
      sym_value,
    STATE(93), 1,
      sym_expression,
    ACTIONS(9), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(15), 2,
      sym_float,
      sym_string,
    STATE(82), 5,
      sym__arithmetic_expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_call_expression,
      sym_primary_expression,
  [447] = 9,
    ACTIONS(11), 1,
      sym_variable,
    ACTIONS(17), 1,
      sym_integer,
    STATE(86), 1,
      sym_boolean,
    STATE(88), 1,
      sym_value,
    STATE(109), 1,
      sym_expression,
    ACTIONS(9), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(15), 2,
      sym_float,
      sym_string,
    STATE(82), 5,
      sym__arithmetic_expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_call_expression,
      sym_primary_expression,
  [482] = 9,
    ACTIONS(11), 1,
      sym_variable,
    ACTIONS(17), 1,
      sym_integer,
    STATE(86), 1,
      sym_boolean,
    STATE(88), 1,
      sym_value,
    STATE(95), 1,
      sym_expression,
    ACTIONS(9), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(15), 2,
      sym_float,
      sym_string,
    STATE(82), 5,
      sym__arithmetic_expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_call_expression,
      sym_primary_expression,
  [517] = 2,
    ACTIONS(163), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(165), 7,
      anon_sym_if,
      anon_sym_else,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [535] = 3,
    ACTIONS(171), 1,
      anon_sym_else,
    ACTIONS(167), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(169), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [555] = 3,
    ACTIONS(177), 1,
      anon_sym_else,
    ACTIONS(173), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(175), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [575] = 2,
    ACTIONS(179), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(181), 7,
      anon_sym_if,
      anon_sym_else,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [593] = 2,
    ACTIONS(183), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(185), 7,
      anon_sym_if,
      anon_sym_else,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [611] = 2,
    ACTIONS(187), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(189), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [628] = 3,
    STATE(53), 1,
      aux_sym_call_expression_repeat1,
    STATE(84), 1,
      sym_call,
    ACTIONS(191), 10,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [647] = 4,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    STATE(46), 1,
      aux_sym_call_expression_repeat1,
    STATE(84), 1,
      sym_call,
    ACTIONS(193), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [668] = 5,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    STATE(46), 1,
      aux_sym_call_expression_repeat1,
    STATE(84), 1,
      sym_call,
    ACTIONS(197), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(193), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [691] = 2,
    ACTIONS(179), 5,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(181), 7,
      anon_sym_if,
      anon_sym_else,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [708] = 2,
    ACTIONS(199), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(201), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [725] = 2,
    ACTIONS(163), 5,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(165), 7,
      anon_sym_if,
      anon_sym_else,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [742] = 2,
    ACTIONS(183), 5,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(185), 7,
      anon_sym_if,
      anon_sym_else,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [759] = 4,
    ACTIONS(205), 1,
      anon_sym_LPAREN,
    STATE(53), 1,
      aux_sym_call_expression_repeat1,
    STATE(84), 1,
      sym_call,
    ACTIONS(203), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [780] = 3,
    ACTIONS(212), 1,
      anon_sym_else,
    ACTIONS(208), 5,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(210), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [799] = 2,
    ACTIONS(214), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(216), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [816] = 2,
    ACTIONS(218), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(220), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [833] = 2,
    ACTIONS(222), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(224), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [850] = 2,
    ACTIONS(226), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(228), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [867] = 3,
    ACTIONS(230), 1,
      anon_sym_else,
    ACTIONS(167), 5,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(169), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [886] = 2,
    ACTIONS(232), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(234), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [903] = 2,
    ACTIONS(236), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(238), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [920] = 4,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    STATE(46), 1,
      aux_sym_call_expression_repeat1,
    STATE(84), 1,
      sym_call,
    ACTIONS(240), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [941] = 3,
    ACTIONS(242), 1,
      anon_sym_else,
    ACTIONS(208), 5,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(210), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [960] = 3,
    ACTIONS(244), 1,
      anon_sym_else,
    ACTIONS(173), 5,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(175), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [979] = 2,
    ACTIONS(92), 5,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(246), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [995] = 2,
    ACTIONS(222), 5,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(224), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [1011] = 2,
    ACTIONS(179), 5,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(181), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [1027] = 2,
    ACTIONS(163), 5,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(165), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [1043] = 2,
    ACTIONS(183), 5,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(185), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [1059] = 2,
    ACTIONS(179), 5,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(181), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [1075] = 2,
    ACTIONS(187), 5,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(189), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [1091] = 2,
    ACTIONS(218), 5,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(220), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [1107] = 2,
    ACTIONS(226), 5,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(228), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [1123] = 2,
    ACTIONS(199), 5,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(201), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [1139] = 2,
    ACTIONS(214), 5,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(216), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [1155] = 2,
    ACTIONS(183), 5,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(185), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [1171] = 2,
    ACTIONS(232), 5,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(234), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [1187] = 2,
    ACTIONS(236), 5,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(238), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [1203] = 2,
    ACTIONS(163), 5,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float,
      sym_string,
    ACTIONS(165), 6,
      anon_sym_if,
      anon_sym_let,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
  [1219] = 1,
    ACTIONS(248), 10,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1232] = 1,
    ACTIONS(250), 10,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1245] = 1,
    ACTIONS(252), 10,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1258] = 1,
    ACTIONS(254), 10,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1271] = 1,
    ACTIONS(256), 10,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1284] = 1,
    ACTIONS(258), 10,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1297] = 1,
    ACTIONS(260), 10,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1310] = 1,
    ACTIONS(262), 10,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1323] = 1,
    ACTIONS(264), 10,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1336] = 7,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(270), 1,
      anon_sym_RPAREN,
    STATE(46), 1,
      aux_sym_call_expression_repeat1,
    STATE(84), 1,
      sym_call,
    ACTIONS(197), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(266), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1360] = 7,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    ACTIONS(272), 1,
      anon_sym_RBRACE,
    ACTIONS(274), 1,
      anon_sym_SEMI,
    STATE(46), 1,
      aux_sym_call_expression_repeat1,
    STATE(84), 1,
      sym_call,
    ACTIONS(197), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(266), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1384] = 7,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(276), 1,
      anon_sym_RPAREN,
    STATE(46), 1,
      aux_sym_call_expression_repeat1,
    STATE(84), 1,
      sym_call,
    ACTIONS(197), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(266), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1408] = 7,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    ACTIONS(274), 1,
      anon_sym_SEMI,
    STATE(46), 1,
      aux_sym_call_expression_repeat1,
    STATE(84), 1,
      sym_call,
    ACTIONS(197), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(266), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1432] = 7,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    ACTIONS(278), 1,
      anon_sym_LBRACE,
    STATE(46), 1,
      aux_sym_call_expression_repeat1,
    STATE(63), 1,
      sym_expression_block,
    STATE(84), 1,
      sym_call,
    ACTIONS(197), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(266), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1456] = 7,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    ACTIONS(280), 1,
      anon_sym_LBRACE,
    STATE(46), 1,
      aux_sym_call_expression_repeat1,
    STATE(54), 1,
      sym_expression_block,
    STATE(84), 1,
      sym_call,
    ACTIONS(197), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(266), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1480] = 7,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    ACTIONS(280), 1,
      anon_sym_LBRACE,
    STATE(46), 1,
      aux_sym_call_expression_repeat1,
    STATE(84), 1,
      sym_call,
    STATE(113), 1,
      sym_expression_block,
    ACTIONS(197), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(266), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1504] = 2,
    ACTIONS(284), 4,
      sym_variable,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
    ACTIONS(282), 5,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_RPAREN,
      sym_float,
      sym_string,
  [1518] = 7,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    ACTIONS(274), 1,
      anon_sym_SEMI,
    ACTIONS(286), 1,
      anon_sym_RBRACE,
    STATE(46), 1,
      aux_sym_call_expression_repeat1,
    STATE(84), 1,
      sym_call,
    ACTIONS(197), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(266), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1542] = 7,
    ACTIONS(114), 1,
      anon_sym_RBRACE,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    ACTIONS(274), 1,
      anon_sym_SEMI,
    STATE(46), 1,
      aux_sym_call_expression_repeat1,
    STATE(84), 1,
      sym_call,
    ACTIONS(197), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(266), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1566] = 7,
    ACTIONS(60), 1,
      anon_sym_RBRACE,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    ACTIONS(274), 1,
      anon_sym_SEMI,
    STATE(46), 1,
      aux_sym_call_expression_repeat1,
    STATE(84), 1,
      sym_call,
    ACTIONS(197), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(266), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1590] = 7,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    ACTIONS(274), 1,
      anon_sym_SEMI,
    ACTIONS(288), 1,
      anon_sym_RBRACE,
    STATE(46), 1,
      aux_sym_call_expression_repeat1,
    STATE(84), 1,
      sym_call,
    ACTIONS(197), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(266), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1614] = 7,
    ACTIONS(64), 1,
      anon_sym_RBRACE,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    ACTIONS(274), 1,
      anon_sym_SEMI,
    STATE(46), 1,
      aux_sym_call_expression_repeat1,
    STATE(84), 1,
      sym_call,
    ACTIONS(197), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(266), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1638] = 7,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    ACTIONS(274), 1,
      anon_sym_SEMI,
    ACTIONS(290), 1,
      anon_sym_RBRACE,
    STATE(46), 1,
      aux_sym_call_expression_repeat1,
    STATE(84), 1,
      sym_call,
    ACTIONS(197), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(266), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1662] = 6,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    STATE(46), 1,
      aux_sym_call_expression_repeat1,
    STATE(84), 1,
      sym_call,
    ACTIONS(197), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(266), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1683] = 6,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    ACTIONS(292), 1,
      anon_sym_SEMI,
    STATE(46), 1,
      aux_sym_call_expression_repeat1,
    STATE(84), 1,
      sym_call,
    ACTIONS(197), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(266), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1704] = 6,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    ACTIONS(294), 1,
      anon_sym_LBRACE,
    STATE(46), 1,
      aux_sym_call_expression_repeat1,
    STATE(84), 1,
      sym_call,
    ACTIONS(197), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(266), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1725] = 6,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    ACTIONS(296), 1,
      anon_sym_SEMI,
    STATE(46), 1,
      aux_sym_call_expression_repeat1,
    STATE(84), 1,
      sym_call,
    ACTIONS(197), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(266), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1746] = 6,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    ACTIONS(274), 1,
      anon_sym_SEMI,
    STATE(46), 1,
      aux_sym_call_expression_repeat1,
    STATE(84), 1,
      sym_call,
    ACTIONS(197), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(266), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1767] = 6,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    ACTIONS(298), 1,
      anon_sym_SEMI,
    STATE(46), 1,
      aux_sym_call_expression_repeat1,
    STATE(84), 1,
      sym_call,
    ACTIONS(197), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(266), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1788] = 6,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    ACTIONS(300), 1,
      anon_sym_LBRACE,
    STATE(46), 1,
      aux_sym_call_expression_repeat1,
    STATE(84), 1,
      sym_call,
    ACTIONS(197), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(266), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1809] = 2,
    ACTIONS(302), 1,
      anon_sym_LBRACE,
    STATE(45), 1,
      sym_expression_block,
  [1816] = 2,
    ACTIONS(280), 1,
      anon_sym_LBRACE,
    STATE(45), 1,
      sym_expression_block,
  [1823] = 2,
    ACTIONS(304), 1,
      anon_sym_LBRACE,
    STATE(71), 1,
      sym_expression_block,
  [1830] = 2,
    ACTIONS(208), 1,
      anon_sym_SEMI,
    ACTIONS(306), 1,
      anon_sym_else,
  [1837] = 1,
    ACTIONS(308), 1,
      ts_builtin_sym_end,
  [1841] = 1,
    ACTIONS(310), 1,
      anon_sym_LBRACE,
  [1845] = 1,
    ACTIONS(312), 1,
      anon_sym_LBRACE,
  [1849] = 1,
    ACTIONS(314), 1,
      anon_sym_EQ,
  [1853] = 1,
    ACTIONS(316), 1,
      sym_variable,
  [1857] = 1,
    ACTIONS(318), 1,
      anon_sym_EQ,
  [1861] = 1,
    ACTIONS(320), 1,
      anon_sym_LBRACE,
  [1865] = 1,
    ACTIONS(322), 1,
      sym_variable,
  [1869] = 1,
    ACTIONS(324), 1,
      anon_sym_SEMI,
  [1873] = 1,
    ACTIONS(326), 1,
      anon_sym_LBRACE,
  [1877] = 1,
    ACTIONS(328), 1,
      anon_sym_EQ,
  [1881] = 1,
    ACTIONS(330), 1,
      sym_variable,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(26)] = 0,
  [SMALL_STATE(27)] = 41,
  [SMALL_STATE(28)] = 82,
  [SMALL_STATE(29)] = 123,
  [SMALL_STATE(30)] = 161,
  [SMALL_STATE(31)] = 199,
  [SMALL_STATE(32)] = 237,
  [SMALL_STATE(33)] = 272,
  [SMALL_STATE(34)] = 307,
  [SMALL_STATE(35)] = 342,
  [SMALL_STATE(36)] = 377,
  [SMALL_STATE(37)] = 412,
  [SMALL_STATE(38)] = 447,
  [SMALL_STATE(39)] = 482,
  [SMALL_STATE(40)] = 517,
  [SMALL_STATE(41)] = 535,
  [SMALL_STATE(42)] = 555,
  [SMALL_STATE(43)] = 575,
  [SMALL_STATE(44)] = 593,
  [SMALL_STATE(45)] = 611,
  [SMALL_STATE(46)] = 628,
  [SMALL_STATE(47)] = 647,
  [SMALL_STATE(48)] = 668,
  [SMALL_STATE(49)] = 691,
  [SMALL_STATE(50)] = 708,
  [SMALL_STATE(51)] = 725,
  [SMALL_STATE(52)] = 742,
  [SMALL_STATE(53)] = 759,
  [SMALL_STATE(54)] = 780,
  [SMALL_STATE(55)] = 799,
  [SMALL_STATE(56)] = 816,
  [SMALL_STATE(57)] = 833,
  [SMALL_STATE(58)] = 850,
  [SMALL_STATE(59)] = 867,
  [SMALL_STATE(60)] = 886,
  [SMALL_STATE(61)] = 903,
  [SMALL_STATE(62)] = 920,
  [SMALL_STATE(63)] = 941,
  [SMALL_STATE(64)] = 960,
  [SMALL_STATE(65)] = 979,
  [SMALL_STATE(66)] = 995,
  [SMALL_STATE(67)] = 1011,
  [SMALL_STATE(68)] = 1027,
  [SMALL_STATE(69)] = 1043,
  [SMALL_STATE(70)] = 1059,
  [SMALL_STATE(71)] = 1075,
  [SMALL_STATE(72)] = 1091,
  [SMALL_STATE(73)] = 1107,
  [SMALL_STATE(74)] = 1123,
  [SMALL_STATE(75)] = 1139,
  [SMALL_STATE(76)] = 1155,
  [SMALL_STATE(77)] = 1171,
  [SMALL_STATE(78)] = 1187,
  [SMALL_STATE(79)] = 1203,
  [SMALL_STATE(80)] = 1219,
  [SMALL_STATE(81)] = 1232,
  [SMALL_STATE(82)] = 1245,
  [SMALL_STATE(83)] = 1258,
  [SMALL_STATE(84)] = 1271,
  [SMALL_STATE(85)] = 1284,
  [SMALL_STATE(86)] = 1297,
  [SMALL_STATE(87)] = 1310,
  [SMALL_STATE(88)] = 1323,
  [SMALL_STATE(89)] = 1336,
  [SMALL_STATE(90)] = 1360,
  [SMALL_STATE(91)] = 1384,
  [SMALL_STATE(92)] = 1408,
  [SMALL_STATE(93)] = 1432,
  [SMALL_STATE(94)] = 1456,
  [SMALL_STATE(95)] = 1480,
  [SMALL_STATE(96)] = 1504,
  [SMALL_STATE(97)] = 1518,
  [SMALL_STATE(98)] = 1542,
  [SMALL_STATE(99)] = 1566,
  [SMALL_STATE(100)] = 1590,
  [SMALL_STATE(101)] = 1614,
  [SMALL_STATE(102)] = 1638,
  [SMALL_STATE(103)] = 1662,
  [SMALL_STATE(104)] = 1683,
  [SMALL_STATE(105)] = 1704,
  [SMALL_STATE(106)] = 1725,
  [SMALL_STATE(107)] = 1746,
  [SMALL_STATE(108)] = 1767,
  [SMALL_STATE(109)] = 1788,
  [SMALL_STATE(110)] = 1809,
  [SMALL_STATE(111)] = 1816,
  [SMALL_STATE(112)] = 1823,
  [SMALL_STATE(113)] = 1830,
  [SMALL_STATE(114)] = 1837,
  [SMALL_STATE(115)] = 1841,
  [SMALL_STATE(116)] = 1845,
  [SMALL_STATE(117)] = 1849,
  [SMALL_STATE(118)] = 1853,
  [SMALL_STATE(119)] = 1857,
  [SMALL_STATE(120)] = 1861,
  [SMALL_STATE(121)] = 1865,
  [SMALL_STATE(122)] = 1869,
  [SMALL_STATE(123)] = 1873,
  [SMALL_STATE(124)] = 1877,
  [SMALL_STATE(125)] = 1881,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(118),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(125),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(121),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_if_statement_repeat1, 2), SHIFT_REPEAT(38),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_if_statement_repeat1, 2),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_if_statement_repeat1, 2), SHIFT_REPEAT(121),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_if_statement_repeat1, 2), SHIFT_REPEAT(32),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_if_statement_repeat1, 2), SHIFT_REPEAT(88),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_if_statement_repeat1, 2), SHIFT_REPEAT(87),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_if_statement_repeat1, 2), SHIFT_REPEAT(86),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_if_statement_repeat1, 2), SHIFT_REPEAT(86),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(33),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(118),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(32),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(88),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(87),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(86),
  [86] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(86),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_block_repeat1, 2), SHIFT_REPEAT(33),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_block_repeat1, 2),
  [94] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_block_repeat1, 2), SHIFT_REPEAT(125),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_block_repeat1, 2), SHIFT_REPEAT(32),
  [100] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_block_repeat1, 2), SHIFT_REPEAT(88),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_block_repeat1, 2), SHIFT_REPEAT(87),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_block_repeat1, 2), SHIFT_REPEAT(86),
  [109] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_block_repeat1, 2), SHIFT_REPEAT(86),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, .production_id = 8), SHIFT_REPEAT(32),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, .production_id = 8),
  [145] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_call_repeat1, 2, .production_id = 8), SHIFT_REPEAT(88),
  [148] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_call_repeat1, 2, .production_id = 8), SHIFT_REPEAT(87),
  [151] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, .production_id = 8), SHIFT_REPEAT(86),
  [154] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_call_repeat1, 2, .production_id = 8), SHIFT_REPEAT(86),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_block, 3),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_block, 3),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, .production_id = 9),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 5, .production_id = 9),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(120),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 4, .production_id = 4),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 4, .production_id = 4),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(123),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_block, 4),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_block, 4),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_block, 2),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_block, 2),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_if_declaration, 8, .production_id = 15),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_if_declaration, 8, .production_id = 15),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 2, .production_id = 2),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_declaration, 5),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_declaration, 5),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_expression_repeat1, 2, .production_id = 3),
  [205] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_expression_repeat1, 2, .production_id = 3), SHIFT_REPEAT(27),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_if_declaration, 6, .production_id = 11),
  [210] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_if_declaration, 6, .production_id = 11),
  [212] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 7, .production_id = 12),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 7, .production_id = 12),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 9, .production_id = 16),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 9, .production_id = 16),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 2),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 2),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 8, .production_id = 13),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 8, .production_id = 13),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 8, .production_id = 14),
  [238] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 8, .production_id = 14),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2),
  [242] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [244] = {.entry = {.count = 1, .reusable = false}}, SHIFT(115),
  [246] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expression_block_repeat1, 2),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, .production_id = 6),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, .production_id = 7),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_expression_repeat1, 1, .production_id = 1),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, .production_id = 10),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_expression, 1),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, .production_id = 5),
  [284] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_call_repeat1, 2, .production_id = 5),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [308] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_vicuna(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
